#### trajectory_visualization.ipynb
by: 
- Ridha Alkhabaz (ridhama2@illinois.edu)
- Lloyd Fernandes (lloydf2@illinois.edu)

Project director: Richard Sowers

r-sowers@illinois.edu https://publish.illinois.edu/r-sowers/

Copyright 2019 University of Illinois Board of Trustees. All Rights Reserved. Licensed under the MIT license

# Visualizing trajectory data

In [2]:
import pandas as pd
import random
import pydeck as pdk
import json

##### Here we would be visualizing the data for block 4 between 8:30 - 9:00 on 24/10/2018

In [5]:
df = pd.read_pickle("block4_1.pkl")
df.head()

               lat        lon    speed  lon_acc  lat_acc type  traveled_d  \
id time
1  0.00  37.981384  23.734019  26.3600   0.0625  -0.0121  Bus      156.25
   0.04  37.981386  23.734021  26.3634  -0.0149  -0.0141  Bus      156.25
   0.08  37.981387  23.734024  26.3578  -0.0625  -0.0160  Bus      156.25
   0.12  37.981389  23.734027  26.3454  -0.1101  -0.0179  Bus      156.25
   0.16  37.981390  23.734030  26.3229  -0.2023  -0.0199  Bus      156.25

         avg_speed
id time
1  0.00   5.227568
   0.04   5.227568
   0.08   5.227568
   0.12   5.227568
   0.16   5.227568

In [7]:
#processing trajectories
df = df.reset_index()
coordinates = [[k,[[i, j] for i,j in zip(df[df['id'] == k]['lon'], df[df['id'] == k]['lat'])],list(df[df['id'] == k].time)] for k in df.id.unique()]
id,coordinate_list,timestamp = zip(*coordinates)
dfx = pd.DataFrame({"id" : id,"coordinates": coordinate_list, "timestamps" : timestamp})
dfx.head()

,id,coordinates,timestamps
0,1,"[[23.734019, 37.981384], [23.734021, 37.981386...","[0.0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28,..."
1,2,"[[23.733991, 37.98315], [23.733994, 37.983151]...","[0.0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28,..."
2,3,"[[23.733895, 37.981945], [23.733895, 37.981945...","[0.0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28,..."
3,4,"[[23.734397, 37.982196], [23.734397, 37.982196...","[0.0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28,..."
4,5,"[[23.734456, 37.981822], [23.734456, 37.981821...","[0.0, 0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28,..."

In [8]:
#generating unique colour for each trajectory
X=np.random.randint(10,20)
dfx['color'] = [(np.random.randint(1,254),np.random.randint(1,254),np.random.randint(1,254)) for i in dfx.id.unique()]

In [12]:
#defining layer object for pydeck
layer = pdk.Layer(
    "TripsLayer",
    dfx,
    get_path="coordinates",
    get_timestamps="timestamp",
    get_color="color",
    opacity=0.5,
    width_min_pixels=2,
    rounded=True,
    trail_length=600,
    current_time=50,
) 
view_state = pdk.ViewState(latitude=37.981384, longitude=23.734019, zoom=17, bearing=0, pitch=45)

In [ ]:
#visualizing the dataset
r = pdk.Deck(layers=layer, initial_view_state=view_state)
r.to_html("block_4_trajectories.html")